%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(nefitproto).
-define(nefitproto, true).

-define(nefitproto_gpb_version, "4.8.0").

-ifndef('CLIENTTOSERVERLOGIN_PB_H').
-define('CLIENTTOSERVERLOGIN_PB_H', true).
-record('ClientToServerLogin',
        {username               :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('CLIENTTOSERVERREGISTER_PB_H').
-define('CLIENTTOSERVERREGISTER_PB_H', true).
-record('ClientToServerRegister',
        {username               :: iodata(),        % = 1
         password               :: iodata(),        % = 2
         clientType             :: 'IMPORTER' | 'MANUFACTURER' | integer() % = 3, enum ClientType
        }).
-endif.

-ifndef('SERVERTOCLIENTAUTH_PB_H').
-define('SERVERTOCLIENTAUTH_PB_H', true).
-record('ServerToClientAuth',
        {ok                     :: boolean() | 0 | 1, % = 1
         clientType             :: 'IMPORTER' | 'MANUFACTURER' | integer() | undefined, % = 2, enum ClientType
         errorMessage           :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('MSGAUTH_PB_H').
-define('MSGAUTH_PB_H', true).
-record('MsgAuth',
        {name                   :: iodata(),        % = 1
         pass                   :: iodata(),        % = 2
         ctype                  :: 'MANUFACTURER' | 'IMPORTER' | integer(), % = 3, enum MsgAuth.ClientType
         mtype = 'LOGIN'        :: 'LOGIN' | 'REGISTER' | integer() % = 4, enum MsgAuth.MsgType
        }).
-endif.

-ifndef('MSGACK_PB_H').
-define('MSGACK_PB_H', true).
-record('MsgAck',
        {ok                     :: boolean() | 0 | 1, % = 1
         msg                    :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('DISPONIBILITYS_PB_H').
-define('DISPONIBILITYS_PB_H', true).
-record('DisponibilityS',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         minimum                :: integer(),       % = 3, 32 bits
         maximum                :: integer(),       % = 4, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 5
         period                 :: integer()        % = 6, 32 bits
        }).
-endif.

-ifndef('DISPONIBILITYN_PB_H').
-define('DISPONIBILITYN_PB_H', true).
-record('DisponibilityN',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         minimum                :: integer(),       % = 3, 32 bits
         maximum                :: integer(),       % = 4, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 5
         period                 :: integer()        % = 6, 32 bits
        }).
-endif.

-ifndef('ORDERS_PB_H').
-define('ORDERS_PB_H', true).
-record('OrderS',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         quant                  :: integer(),       % = 3, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 4
         nameI                  :: iodata()         % = 5
        }).
-endif.

-ifndef('ORDERN_PB_H').
-define('ORDERN_PB_H', true).
-record('OrderN',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         quant                  :: integer(),       % = 3, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 4
         nameI                  :: iodata()         % = 5
        }).
-endif.

-ifndef('ORDERACKS_PB_H').
-define('ORDERACKS_PB_H', true).
-record('OrderAckS',
        {ack                    :: boolean() | 0 | 1, % = 1
         msg                    :: iodata() | undefined, % = 2
         nameI                  :: iodata(),        % = 3
         outdated               :: boolean() | 0 | 1 % = 4
        }).
-endif.

-ifndef('ORDERACKI_PB_H').
-define('ORDERACKI_PB_H', true).
-record('OrderAckI',
        {ack                    :: boolean() | 0 | 1, % = 1
         msg                    :: iodata() | undefined, % = 2
         outdated               :: boolean() | 0 | 1 % = 3
        }).
-endif.

-ifndef('SUBS_PB_H').
-define('SUBS_PB_H', true).
-record('SubS',
        {nameI                  :: iodata(),        % = 1
         subs = []              :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('SUBN_PB_H').
-define('SUBN_PB_H', true).
-record('SubN',
        {nameI                  :: iodata(),        % = 1
         subs = []              :: [iodata()] | undefined % = 2
        }).
-endif.

-ifndef('PRODUCTIONS_PB_H').
-define('PRODUCTIONS_PB_H', true).
-record('ProductionS',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         quant                  :: integer(),       % = 3, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan % = 4
        }).
-endif.

-ifndef('PRODUCTIONM_PB_H').
-define('PRODUCTIONM_PB_H', true).
-record('ProductionM',
        {nameP                  :: iodata(),        % = 1
         quant                  :: integer(),       % = 2, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan % = 3
        }).
-endif.

-ifndef('RESULTS_PB_H').
-define('RESULTS_PB_H', true).
-record('ResultS',
        {result                 :: boolean() | 0 | 1, % = 1
         msg                    :: iodata(),        % = 2
         nameI                  :: iodata()         % = 3
        }).
-endif.

-ifndef('RESULTI_PB_H').
-define('RESULTI_PB_H', true).
-record('ResultI',
        {result                 :: boolean() | 0 | 1, % = 1
         msg                    :: iodata()         % = 2
        }).
-endif.

-ifndef('INFOS_PB_H').
-define('INFOS_PB_H', true).
-record('InfoS',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         minimum                :: integer(),       % = 3, 32 bits
         maximum                :: integer(),       % = 4, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 5
         period                 :: integer(),       % = 6, 32 bits
         nameI                  :: iodata()         % = 7
        }).
-endif.

-ifndef('INFOI_PB_H').
-define('INFOI_PB_H', true).
-record('InfoI',
        {nameM                  :: iodata(),        % = 1
         nameP                  :: iodata(),        % = 2
         minimum                :: integer(),       % = 3, 32 bits
         maximum                :: integer(),       % = 4, 32 bits
         value                  :: float() | integer() | infinity | '-infinity' | nan, % = 5
         period                 :: integer()        % = 6, 32 bits
        }).
-endif.

-ifndef('SERVER_PB_H').
-define('SERVER_PB_H', true).
-record('Server',
        {msg                    :: {m1, nefitproto:'DisponibilityS'()} | {m2, nefitproto:'OrderS'()} | {m3, nefitproto:'SubS'()} | {m4, nefitproto:'ResultS'()} | {m5, nefitproto:'InfoS'()} | {m6, nefitproto:'ProductionS'()} | {m7, nefitproto:'OrderAckS'()} | undefined % oneof
        }).
-endif.

-ifndef('IMPORTER_PB_H').
-define('IMPORTER_PB_H', true).
-record('Importer',
        {msg                    :: {ordack, nefitproto:'OrderAckI'()} | {result, nefitproto:'ResultI'()} | {info, nefitproto:'InfoI'()} | undefined % oneof
        }).
-endif.

-ifndef('NEGOTIATOR_PB_H').
-define('NEGOTIATOR_PB_H', true).
-record('Negotiator',
        {msg                    :: {sub, nefitproto:'SubN'()} | {order, nefitproto:'OrderN'()} | {disponibility, nefitproto:'DisponibilityN'()} | undefined % oneof
        }).
-endif.

-endif.
